### ISSUE TITLE
After version 0.0.13 is updated, some notes will disappear in preview mode

### ISSUE THREAD

**Issue by jiaochenglong** [Aidurber/obsidian-plugin-dynamic-toc#13]
After version 0.0.13 is updated, some notes will disappear in preview mode

**Comment by Aidurber** [comment]
I was unable to reproduce the issue you had but there was a nasty bug lurking that I've hot fixed. Can you update to 0.0.14 and let me know if you encounter any issues.

**Comment by realityvrc** [comment]
After Obsidian-Kanban updated from version 1.0.15 to version 1.0.20 it started ti throw an error on any non-empty kanban.
I did some digging and it turns out it conflicts with Dynamic Table Of Contents plugin (v0.0.13)
Disabling Dynamic Table Of Contents plugin or rolling back Dynamic Table Of Contents plugin to version 0.0.11
or rolling back Obsidian-Kanban to 1.0.15 fixed the issue.

Update: Installed new version v0.0.14 and the error is gone

**Comment by Aidurber** [comment]
Thanks @realityvrc! Yeah the bug was really dumb and I'm sorry about that!
