### ISSUE TITLE
Export do PDF does not create document links

### ISSUE THREAD

**Issue by manfredbjorlin** [Aidurber/obsidian-plugin-dynamic-toc#18]
When exporting to PDF from Obsidian the TOC does not appear to be document links in the same way as when making footnotes.

**Comment by Aidurber** [comment]
Hi @manfredbjorlin, I've finally got around to looking into this. Just going to do a brain dump. 

When Obsidian converts the markdown into HTML, it does not add an ID to the header elements.
<img src="https://user-images.githubusercontent.com/5732291/140179287-2748b757-ea99-4377-afed-ebda891724b0.jpg" alt="Header element HTML" width="500"  />

In order to link inside a document, the target element needs an ID. That ID becomes the href for the anchor tag. This is clear when you take a look at how footnotes work. 


<img src="https://user-images.githubusercontent.com/5732291/140179378-50a2b0b4-04e1-4adf-a29b-2ebe7208941c.jpg" alt="Foot note element HTML" width="500"  />

Obsidian generates a unique ID for each footnote, which allows for the link to work. 


That being said I _could_ give headers a similar treatment, I'm unsure in the amount of work required.

**Comment by Aidurber** [comment]
After much pain, I've discovered it's not possible at the moment. 

It's a known issue in Obsidian that same document links aren't functional in PDFs. With the exception of footnotes (for some reason). 

Source: https://forum.obsidian.md/t/pdf-export-make-links-within-same-document-functional/16384

In the mean time I'm afraid there isn't much we can do. I'm going to close. I've subscribed to that feature request, if that changes I'll take another look at this.
