### ISSUE TITLE
Having a jumps in heading levels ruins the indentation

### ISSUE THREAD

**Issue by Archie-2021** [Aidurber/obsidian-plugin-dynamic-toc#26]
For example. I like to embed the TOC and some dataview metadata stuff at the top of my notes in a lvl4 heading so that I can fold it out of the way. But if I do that all the indentation above the lvl 4 get removed.

**Comment by Aidurber** [comment]
Can you share with me an example + a screenshot if at all possible.

**Comment by Archie-2021** [comment]
> Can you share with me an example + a screenshot if at all possible. 

Look how lvl1 heading shown at lvl2 becauae Toc on top of it starts at lvl2

![Screenshot 2021-12-20 092311.png](https://user-images.githubusercontent.com/85870778/146718586-aa49223d-9c62-47cf-84f2-930af47bcfb7.png)

![Screenshot 2021-12-20 092246.png](https://user-images.githubusercontent.com/85870778/146718593-a1dc03b8-0d08-43fd-9d22-76bc1deac6e1.png)

**Comment by Aidurber** [comment]
### Short Answer
You cannot have a level 2 heading first in the document and then have a level 1 heading. 

### Detailed Answer
I don't think this can be fixed. The first heading in a document should be the lowest (level 1). It's quite difficult to explain so hopefully images will help. 

In this example, I moved toc to level 1, this fixed the indentation. 
![CleanShot 2021-12-21 at 11 04 44@2x](https://user-images.githubusercontent.com/5732291/146920490-b1eeeaf2-a8b4-4fed-88d0-5be2be51dce5.jpg)
 
The logic that is in play is: 
1. Find all headings in a document
2. Get take the first heading
3. Get the level of that heading, this sets the basis of the indentation (we need indentation to render markdown lists correctly)
4. For each heading we subtract the first headings level found in step 3 this is because we cannot have a list that has a first item that is indented more than the subsequent items, it produces invalid markdown. 

So in your example: 
- toc = level 2
    - 2 - 2 = 0 (no indentation)
- lvl1 = level 1
    - 1 - 2 = -1 (negative indentation isn't a think in markdown so it's 0)

Removing the subtract logic produces invalid markdown which won't render

![CleanShot 2021-12-21 at 11 06 59@2x](https://user-images.githubusercontent.com/5732291/146921064-c1f65b1d-19d7-4211-8618-3b11c973f223.jpg)


### Recommendation

You are using headings a little unconventionally. Headings aren't for style, they provide lexical meaning to a document. 

If your documents were structured like this, by having a top level 1 heading, that will fix your issue.
With the logic that we're forced to apply by subtracting **the first** headings level in a document by a headings level: 
- page title - level 1
    - 1 - 1 = 0 (no indentation)
- toc - level 2
    - 2 - 1 = 1 (one level if indentation)
- lvl1 - level 2
    - 2 - 1 = 1 

```md
# Page title
## toc
## lvl1
### lvl2
```

That will fix your issue. Alternatively, make `toc` a level 1 header

**Comment by Archie-2021** [comment]
> ### Short Answer
> You cannot have a level 2 heading first in the document and then have a level 1 heading.
> 
> ### Detailed Answer
> I don't think this can be fixed. The first heading in a document should be the lowest (level 1). It's quite difficult to explain so hopefully images will help.
> 
> In this example, I moved toc to level 1, this fixed the indentation. ![CleanShot 2021-12-21 at 11 04 44@2x](https://user-images.githubusercontent.com/5732291/146920490-b1eeeaf2-a8b4-4fed-88d0-5be2be51dce5.jpg)
> 
> The logic that is in play is:
> 
> 1. Find all headings in a document
> 2. Get take the first heading
> 3. Get the level of that heading, this sets the basis of the indentation (we need indentation to render markdown lists correctly)
> 4. For each heading we subtract the first headings level found in step 3 this is because we cannot have a list that has a first item that is indented more than the subsequent items, it produces invalid markdown.
> 
> So in your example:
> 
> * toc = level 2
>   
>   * 2 - 2 = 0 (no indentation)
> * lvl1 = level 1
>   
>   * 1 - 2 = -1 (negative indentation isn't a think in markdown so it's 0)
> 
> Removing the subtract logic produces invalid markdown which won't render
> 
> ![CleanShot 2021-12-21 at 11 06 59@2x](https://user-images.githubusercontent.com/5732291/146921064-c1f65b1d-19d7-4211-8618-3b11c973f223.jpg)
> 
> ### Recommendation
> You are using headings a little unconventionally. Headings aren't for style, they provide lexical meaning to a document.
> 
> If your documents were structured like this, by having a top level 1 heading, that will fix your issue. With the logic that we're forced to apply by subtracting **the first** headings level in a document by a headings level:
> 
> * page title - level 1
>   
>   * 1 - 1 = 0 (no indentation)
> * toc - level 2
>   
>   * 2 - 1 = 1 (one level if indentation)
> * lvl1 - level 2
>   
>   * 2 - 1 = 1
> 
> ```lisp
> # Page title
> ## toc
> ## lvl1
> ### lvl2
> ```
> 
> That will fix your issue. Alternatively, make `toc` a level 1 header

Thanks for your detailed explanation, I agree that my use of heading here is a bit unconventional but the thing is that I like folding and unfolding and separating document in manageable and referenceable chunks a lot and it is the only heading that I can do it in markdown. I will use a first level heading at the top for putting front matter out of the way after this. it is going to be a bit distracting and ugly but would do the job.
