### ISSUE TITLE
Using dynamic toc causes some parts of the file uneditable

### ISSUE THREAD

**Issue by ag1410** [Aidurber/obsidian-plugin-dynamic-toc#41]
I have a file in which I am using headings and sub-headings as well as images. When using the dynamic toc to generate a table of contents at the top, some bulleted and indented bulleted text was rendered uneditable. I wasn't even able to select the text. the cursor would just jump to the last part of the last heading in the page

**Comment by Aidurber** [comment]
1. Are you using the codeblock approach "```toc" or the external renderers?
2. Is this happening in live preview or just in full preview?
3. Can you provide an example document so I can try and replicate the issue?
4. Are you on the latest version of the plugin?

**Comment by LuoJimyang** [comment]
Hello, Aidurber!
I met the same issue too.
But it's so strange that the issue is fixed after I delete a large chunk of text(no the text been frozen) and restore it by using CMD+Z, the text that was frozen can be edited again.
Here is a reply to your comment.
1. I use codeblock. Below is my codeblock.
```toc

```
2. Happening in live preview.  I can edit other text, so I think I am in live preview. Full preview cannot edit text.
3. Pleause download the md file. But the issue CANNOT occur now. 
[toctest.md](https://github.com/Aidurber/obsidian-plugin-dynamic-toc/files/8039478/toctest.md)
Below is the text which been frozen and uneditable before.
![image](https://user-images.githubusercontent.com/86758544/153369769-965badc1-83b3-4ba5-810f-c97aa6821e8a.png)

4. Plugin version is 0.0.26

**Comment by LuoJimyang** [comment]
I met this issue again. The text in the screenshot with red box cannot click by left mouse button. 
![image](https://user-images.githubusercontent.com/86758544/153377275-4a6e5167-c11a-4a30-bdad-4a9c1c77b94f.png)

I make a screenrecord. You can check it.
They are frozen and cannot be selected by mouse, but can use keyboard ← & → to select.

https://user-images.githubusercontent.com/86758544/153378499-cb85c21f-6543-41a1-b06a-75c852ede48a.mp4

Please check the md below.
[TEST.md](https://github.com/Aidurber/obsidian-plugin-dynamic-toc/files/8039742/TEST.md)

**Comment by Aidurber** [comment]
@LuoJimyang That's extremely helpful, thank you for sharing such detailed reproduction steps. I'll try and make some time to dig into this.

**Comment by Castleeee** [comment]
same question

**Comment by Aidurber** [comment]
@LuoJimyang I'm afraid I can't reproduce the error. If I can't consistently reproduce the error I'm unable to make a fix. I'm sorry.
